### PUBLIC PROFILE WITH LANGUAGE: Exemple en-US to English
GET http://localhost:8000/api/public/profile/en

###

GET http://localhost:8000/api/auth/test

###

GET http://localhost:8000/api/admin/test
