###
GET http://localhost:8000/api/auth/signed

###
POST http://localhost:8000/api/auth/sign/in HTTP/1.1
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "admin@123456"
}

###
POST http://localhost:8000/api/auth/sign/up HTTP/1.1
content-type: application/json

{
    "amail": "abc@admin.com",
    "password": "123456789",
    "password_confirmation": "123456789",
    "name": "ABC"
}

###
POST http://localhost:8000/api/auth/sign/out HTTP/1.1
content-type: application/json
